### ISSUE TITLE
P1.memo() sometimes returns null when accessed concurrently

### ISSUE THREAD

**Issue by mperry** [functionaljava/functionaljava#105]
Paweł Krupiński reported an issue in the group as per below (https://groups.google.com/forum/#!topic/functionaljava/nSPIBAvAWVY):

Hi.
We started noticing NullPointerExceptions in our code that accessed fj.data.Stream instances concurrently.

I was able to trace it down to P1.memo() creating a P1 that sometimes returns null from ._1() call when accessed concurrently.
Here's how to reproduce it (sometimes you need to run it multiple times) on Java 8 and functionaljava 4.2:

```
final P1<String> p1 = P.p("Bla").memo();
ExecutorService executorService = Executors.newCachedThreadPool();
for (int i = 0; i < 1000; i++) {
    executorService.submit(() -> {
        if (p1._1() == null) {
            System.out.println("Null");
        }
    });
}

executorService.shutdown();
executorService.awaitTermination(10, TimeUnit.DAYS);
```

**Comment by knutwalker** [comment]
Hi, I took a stab at this in #106.

**Comment by zot** [comment]
The code looks to me like the caching doesn't work for a _1() will that returns null, i.e. repeated calls to memo() will repeatedly evaluate _1(), contributing to the quadratic execution time that memos were created to avoid.

Maybe the condition should only be based on v == null -- something like this?  I'm using tmp to avoid a potential race condition because I'm not absolutely positive that compiled code is guaranteed to call the constructor before the assignment.  Someone who knows this for sure can remove tmp and shorten this by a line :).

public A _1() {
  if (v != null) return v.get();
  A a = self._1();
  SoftReference<A> tmp = new SoftReference<A>(a);
  v = tmp;
  return a;
}
