### ISSUE TITLE
missing functions on List - (partition, safeHead)

### ISSUE THREAD

**Issue by amarpotghan** [functionaljava/functionaljava#111]
Hey,

I would like to see : 

1. `partition :: (a -> Bool) -> [a] -> ([a], [a])` 
2. `safeHead :: [a] -> Maybe a`

on the List type, thoughts?

**Comment by ms-tg** [comment]
In Scala, is this `List#partition` and `List#headOption`?

**Comment by amarpotghan** [comment]
@ms-tg yup

**Comment by knutwalker** [comment]
`safeHead` or `headOption` is `List#toOption`

**Comment by amarpotghan** [comment]
Ah, Sure. Thanks.

**Comment by tonymorris** [comment]
+1

However, `safeHead` is better written as a `Prism`

https://hackage.haskell.org/package/lens-4.7/docs/Control-Lens-Prism.html

https://hackage.haskell.org/package/lens-4.7/docs/Control-Lens-Cons.html

Note that writing prisms, in general, in Java requires code repetition, due to lack of higher-kinds. The idea here, however, is that `_head` can perform a "safe head retrieval" as well as "safe update head" operation.

**Comment by amarpotghan** [comment]
thanks, it makes sense to me as a Prism! FWIW, can repetition be tolerated?

**Comment by julien-truffaut** [comment]
@tonymorris `safeHead` is not a `Prism` as you cannot recreate the original `List`. However, if you compose `cons: Prism[List[A], (A, List[A])]` with `_1: Lens[(A, B), A]` you get `safeHead`. The result of the composition is an `Optional` (in monocle) or a `Traversal` (in haskell lens if I am not mistaken).

**Comment by jbgi** [comment]
so, with #130, you would get:
```java
  public static <A> Optional<List<A>, A> _head() {
    return optional(
        l -> l.toOption().toEither(nil()),
        a -> l -> l.list(nil(), h -> tail -> cons(a, tail))
        );
  }
```

**Comment by tonymorris** [comment]
@julien-truffaut Yes you are right.

**Comment by mperry** [comment]
Created #161 to add List#partition.
