### ISSUE TITLE
What ordering to use for arbitrary data types

### ISSUE THREAD

**Issue by ysndr** [functionaljava/functionaljava#316]
As `Ord::hashEqualsOrd` is deprecated since #290 I wonder which ordering to use for sets with content different from just primitive data types.
I don't know if I really understood ordering in general but there is no method returning an Odering<A> anymore apart from specifying a completely self written ordering function or having a comparable Datataype

An help is welcome as I'm not really comfortable with using deprecated API ;)

**Comment by jbgi** [comment]
If can you have `Hash`/`Equal` but not `Ord` I suggest you use `HashArrayMappedTrie<K, Unit>` as a Set.
`HashArrayMappedTrie` is a new addition to FJ, so you may find that there is some api missing; please open issues for the one you miss (probably include a wrapper class to use `HashArrayMappedTrie<K, Unit>` more easily as a Set).

But writing one manually should also be made more easy, possibly by introducing a "fluent" api. But you can also convert to a `P` and use `contramap` on `P` ord.

The other possibility is using a code generator, I think https://github.com/immutables/immutables can generate value class that implement Comparable (but that will not work for unconstrained parametric types).

Finally there is https://github.com/derive4j/derive4j that allows you to generate boilerplate for full blown Algebraic Data Types (via church-encoding/visitor-pattern) and I have just finished derivation of FJ type classes `Hash`/`Ord`/`Equal`/`Show` (release tonight) so that will be also an option (and it will work for unconstrained parametric types)

**Comment by jbgi** [comment]
@ysndr See https://github.com/derive4j/derive4j-fj

**Comment by ysndr** [comment]
That seems promising thank you
